# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Sinspired.SubsFree
PackageVersion: 2.1.3
PackageLocale: zh-SG
Publisher: Sinspired
PublisherUrl: https://github.com/sinspired
PublisherSupportUrl: https://github.com/sinspired/subs-check-pro/wiki
Author: Sinspired
PackageName: Subs Free
PackageUrl: https://github.com/sinspired/subs-free
License: MIT License
Copyright: © 2026, Sinspired
ShortDescription: 高性能网络节点检测和管理客户端
Description: 基于 Subs-Check-Pro 内核的跨平台客户端应用，支持 Android 手机，Windows，Linux和Mac。
ReleaseNotes: 请查看 GitHub 发布页面
ReleaseNotesUrl: https://github.com/sinspired/subs-free/releases/tag/v2.1.3
ManifestType: defaultLocale
ManifestVersion: 1.12.0
