# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Sinspired.SubsFree
PackageVersion: 2.1.3
InstallerType: nullsoft
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/sinspired/subs-free/releases/download/v2.1.3/subs-free_windows_x64_setup.exe
  InstallerSha256: 2AE37BEF7AE1C9BFDEC37C0E0EDA30B2E4C211A9FA4473577316F7181A202F0B
ManifestType: installer
ManifestVersion: 1.12.0
